name: Access files
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - user: actions/checkout@v2
      - name: Run build script
      - run: sh ./.github/checkFirl.sh
        shell: bash
        
   
