name: Access files
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: ./.github/scripts/checkFirl.sh
        shell: bash
